
spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: 2.0

accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "John Kenny - Developer"
    email: "johnkenny@eazybank.com"
  onCallSupport:
    - (555) 555-8877
    - (555) 523-8878