services:
  accounts:
    image: "hemanth328/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hemanth11

  loans:
    image: "hemanth328/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hemanth11


  cards:
    image: "hemanth328/cards:s4"
    container_name: cards-ms
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hemanth11

networks:
  hemanth11:
    driver: "bridge"